name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: git fetch --depth=20 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build octotask
        run: npm run build
      - name: Publish documentation
        run: ./script/publish-docs
        env:
          OCTOKITBOT_PAT: ${{ secrets.GITHUB_TOKEN }}
